/**
 * @file    main.c
 * @brief   MicroMaze 3 — STM32F411CEU6 Black Pill
 *          Firmware entry point and peripheral initialisation.
 *
 * @details Responsibilities of this file:
 *            1. HAL and system clock initialisation.
 *            2. All STM32 peripheral configuration (generated by CubeMX
 *               then hand-edited to match pins.h exactly).
 *            3. Module bring-up in dependency order.
 *            4. DIP switch read → mode dispatch.
 *            5. HAL callback routing (timer IRQs → correct modules).
 *
 *          PERIPHERAL CONFIGURATION SUMMARY
 *          ─────────────────────────────────
 *          TIM1  PWM CH1+CH2  PA8/PA9      Motor PWM 20 kHz
 *          TIM2  Encoder      PA0/PA1      Left  encoder (32-bit)
 *          TIM3  Encoder      PB4/PB5      Right encoder (16-bit + OVF)
 *          TIM5  Base timer   —            1 kHz control loop IRQ
 *          ADC1  DMA scan     PA2–PA7,PB0  6 IR receivers + battery
 *          I2C1  400 kHz      PB8/PB9      MPU6500 + SSD1306 OLED
 *          EXTI  PC13         —            MPU6500_INT (wired, unused today)
 *
 *          No onboard LED, no buzzer, no UART1 — all dropped or blocked;
 *          every GPIO on the UFQFPN48 package is committed elsewhere.
 *          OLED display serves as the primary visual status output.
 *
 *          CUBEMX SETTINGS REQUIRED
 *          ─────────────────────────
 *          System Core → SYS → Debug: Serial Wire   ← frees PA15, PB3
 *          TIM1  → PWM Gen CH1+CH2, PSC=0, ARR=4999
 *          TIM2  → Encoder Mode TI1+TI2, Period=0xFFFFFFFF
 *          TIM3  → Encoder Mode TI1+TI2, Period=0xFFFF, NVIC enabled
 *          TIM5  → Timer interrupt, PSC=99, ARR=999, NVIC priority 1
 *          ADC1  → Scan+DMA, 7 ranks, software trigger, circular DMA
 *          I2C1  → Fast mode 400 kHz
 *
 * @author  VDawn
 * @date    2026
 */

#include "main.h"

/* ── Module includes (dependency order — lower layers first) ─────────── */
#include "config.h"
#include "pins.h"
#include "error.h"

/* Utils */
#include "utils.h"

/* Drivers */
#include "motors.h"
#include "encoders.h"
#include "ir.h"
#include "imu.h"
#include "battery.h"
#include "oled.h"
#include "buttons.h"
#include "flash_storage.h"

/* Control */
#include "pid.h"
#include "motion.h"
#include "turn.h"
#include "trajectory.h"
#include "wall_follow.h"

/* Navigation */
#include "maze.h"
#include "floodfill.h"
#include "explorer.h"
#include "speedrun.h"

/* Calibration */
#include "calibration.h"

/* System */
#include "scheduler.h"
#include "modes.h"
#include "diagnostics.h"

/* =========================================================================
 * HAL PERIPHERAL HANDLES
 * Declared here — extern'd in main.h so every module can access them.
 * CubeMX generates these declarations; they are listed here explicitly
 * so the handle-to-peripheral mapping is always visible in one place.
 * ======================================================================= */

TIM_HandleTypeDef  htim1;   /**< Motor PWM  — TIM1 CH1 PA8, CH2 PA9      */
TIM_HandleTypeDef  htim2;   /**< Left  encoder — TIM2 PA0/PA1 (32-bit)   */
TIM_HandleTypeDef  htim3;   /**< Right encoder — TIM3 PB4/PB5 (16-bit)   */
TIM_HandleTypeDef  htim5;   /**< Control loop 1 kHz — TIM5                */
ADC_HandleTypeDef  hadc1;   /**< IR + battery ADC scan — ADC1             */
DMA_HandleTypeDef  hdma_adc1; /**< DMA for ADC1 circular scan             */
I2C_HandleTypeDef  hi2c1;   /**< MPU6500 + OLED — I2C1 PB8/PB9           */

/** Set inside modules_init() when Flash calibration loads successfully;
 *  read back in main() for the oled_show_boot_complete() call, which
 *  needs it but runs after modules_init() returns (mode isn't known
 *  until the DIP switches are read, later still). */
static bool s_cal_loaded = false;

/* =========================================================================
 * PRIVATE FUNCTION PROTOTYPES
 * All init helpers are static — they are internal to this file.
 * ======================================================================= */

static void system_clock_config(void);
static void gpio_init(void);
static void dma_init(void);
static void tim1_pwm_init(void);
static void tim2_encoder_init(void);
static void tim3_encoder_init(void);
static void tim5_ctrl_loop_init(void);
static void adc1_ir_battery_init(void);
static void i2c1_init(void);

static MmResult_t modules_init(void);

/* =========================================================================
 * MAIN ENTRY POINT
 * ======================================================================= */

/**
 * @brief  Firmware entry point.
 *
 * @details Sequence:
 *   1.  HAL_Init          — SysTick, interrupt priority grouping.
 *   2.  system_clock_config — 100 MHz from HSE 25 MHz PLL.
 *   3.  utils_init        — DWT microsecond counter.
 *   4.  Peripheral init   — GPIO, DMA, timers, ADC, I2C, UART.
 *   5.  modules_init      — drivers, control, navigation, system layers.
 *   6.  DIP switch read   — determines which mode to run.
 *   7.  modes_run         — blocking mode dispatcher, never returns.
 *
 * @return int  Never reached (embedded infinite loop).
 */
int main(void)
{
    MmResult_t result;

    /* ── 1. HAL initialisation ─────────────────────────────────────────
     *  Configures SysTick for 1 ms HAL_GetTick(), sets interrupt
     *  priority grouping to NVIC_PRIORITYGROUP_4 (4 bits preemption,
     *  0 bits sub-priority).
     * ────────────────────────────────────────────────────────────────── */
    HAL_Init();

    /* ── 2. System clock: HSE 25 MHz → PLL → 100 MHz ───────────────── */
    system_clock_config();

    /* ── 3. DWT microsecond counter (must be before any delay_us call) */
    utils_init();

    /* ── 4. Peripheral initialisation (order matters) ──────────────── */
    gpio_init();        /* All GPIO directions, speeds, pull-ups        */
    dma_init();         /* DMA controller clocks — must precede ADC     */
    tim1_pwm_init();    /* Motor PWM channels — outputs start at 0 %   */
    tim2_encoder_init();/* Left  encoder (32-bit, PA0/PA1)              */
    tim3_encoder_init();/* Right encoder (16-bit, PB4/PB5) + NVIC      */
    adc1_ir_battery_init(); /* 7-channel DMA circular scan             */
    i2c1_init();        /* MPU6500 + OLED at 400 kHz                   */

    /* ── 5. Module initialisation ───────────────────────────────────── */
    result = modules_init();
    if (result != MM_OK)
    {
        fatal_error_handler(result);
        /* Never returns */
    }

    /* ── 6. Start control loop timer (1 kHz) ───────────────────────── */
    /* Must start AFTER all modules are initialised because the ISR
     * immediately calls motion_1khz_tick() which touches driver state. */
    tim5_ctrl_loop_init();

    /* ── 7. Read DIP switches → select operating mode ──────────────── */
    /* Short delay lets switch inputs settle after power-on.            */
    HAL_Delay(10U);
    uint8_t mode = READ_DIP_SWITCHES();

    oled_show_boot_complete(mode, battery_voltage(), s_cal_loaded);

    /* Announce mode on OLED */
    oled_show_mode(mode);

    /* ── 8. Blocking mode dispatcher ───────────────────────────────── */
    modes_run(mode);

    /* Should never reach here — every mode runs an infinite loop or
     * blocks until its task is complete then halts.                    */
    fatal_error_handler(MM_ERR_GENERAL);

    /* Suppress compiler "control reaches end of non-void function"    */
    return 0;
}

/* =========================================================================
 * MODULE INITIALISATION
 * ======================================================================= */

/**
 * @brief  Initialise all firmware modules in dependency order.
 *
 * @details Each module's init function returns MM_OK on success or an
 *          error code on failure.  Initialisation stops at the first
 *          failure and the error code is returned to main().
 *
 *          Order: Utils → Drivers → Calibration load → Control → Navigation → System
 *
 * @return MM_OK if all modules initialised successfully.
 * @return Error code from the first module that failed.
 */
static MmResult_t modules_init(void)
{
    MmResult_t result;

    /* ── Drivers layer ─────────────────────────────────────────────── */

    motors_init();          /* PWM channels, direction pins, STBY LOW   */
    encoders_init();        /* TIM2 + TIM3 encoder start                */

    result = ir_init();     /* ADC1 DMA start, load cal from Flash      */
    if (result != MM_OK)
    {
        return result;
    }

    result = imu_init(&hi2c1);
    if (result != MM_OK)
    {
        oled_show_error("IMU FAIL", (int32_t)result);
        return result;
    }

    battery_init();

    oled_init(&hi2c1);
    oled_show_boot();

    buttons_init();

    /* ── Flash: load calibration data ─────────────────────────────── */
    result = flash_storage_load_calibration();
    s_cal_loaded = (result == MM_OK);

    /* ── IMU calibration (gyro zero-rate offset) ───────────────────── */
    oled_show_message("GYRO CAL...", "KEEP STILL");

    result = gyro_cal_run();
    if (result != MM_OK)
    {
        return result;
    }

    /* ── Control layer ─────────────────────────────────────────────── */
    motion_init();
    turn_init();
    /* NOTE: trajectory_init() is intentionally NOT called here. It's a
     * per-move setup function (needs real dist_mm/speed_mmps/accel/decel
     * for the specific segment about to run) — every real call site is
     * inside trajectory.c/turn.c at the start of an actual movement, not
     * a one-time boot initializer. Nothing else in the codebase calls
     * it externally either. */
    wall_follow_init();

    /* ── Navigation layer ──────────────────────────────────── */
    maze_init();
    floodfill_init();
    explorer_init();
    speedrun_init();

    /* ── System layer ──────────────────────────────────────────────── */
    modes_init();
    scheduler_init();
    diagnostics_init();

    return MM_OK;
}

/* =========================================================================
 * FATAL ERROR HANDLER
 * ======================================================================= */

/**
 * @brief  Called when a module fails to initialise.
 *
 * @details Disables motors, displays the error code on the OLED,
 *          and halts forever. No onboard LED or buzzer is
 *          available on this board revision (PC13 is committed to
 *          MPU6500_INT) — the OLED is the primary error channel.
 *          Never returns.
 *
 * @param  err  Error code from the failing module (MmResult_t).
 */
void fatal_error_handler(MmResult_t err)
{
    motors_disable();

    oled_show_error("Init failed", (int32_t)err);

    while (1)
    {
        HAL_Delay(800U);
    }
}

/**
 * @brief  Standard CubeMX HAL error hook — see the prototype comment in
 *         main.h. Not currently called anywhere in this project (no
 *         stm32f4xx_it.c exists yet to call it from a HAL error
 *         callback), but implemented now rather than left as a
 *         declared-but-undefined prototype.
 */
void Error_Handler(void)
{
    fatal_error_handler(MM_ERR_DRIVER);
}

/* =========================================================================
 * HAL INTERRUPT CALLBACKS
 * These are called by the STM32 HAL from the appropriate IRQ handlers.
 * The IRQ handler names (TIM5_IRQHandler etc.) are in stm32f4xx_it.c
 * (generated by CubeMX) and call HAL_TIM_IRQHandler(&htim5) which then
 * calls HAL_TIM_PeriodElapsedCallback below.
 * ======================================================================= */

/**
 * @brief  HAL timer period-elapsed callback.
 *
 * @details Routes timer update events to the correct module:
 *            TIM5 → motion_1khz_tick()   (1 kHz control loop)
 *            TIM3 → encoders_tim3_ovf_irq()  (right encoder overflow extend)
 *
 *          Keep this function as short as possible — it runs inside an ISR.
 *          Do not call HAL_Delay() or any blocking function here.
 *
 * @param  htim  Pointer to the timer handle that triggered the callback.
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM5)
    {
        /* 1 kHz control loop: sensors → gyro → PID → motor output      */
        motion_1khz_tick();
    }
    else if (htim->Instance == TIM3)
    {
        /* Extend 16-bit TIM3 right encoder to 32-bit using overflow cnt */
        encoders_tim3_ovf_irq();
    }
}

/**
 * @brief  HAL ADC conversion complete callback (DMA).
 *
 * @details Called when the ADC1 DMA circular buffer completes one full
 *          sweep of all 7 channels (6 IR receivers + battery).
 *          Sets a flag that the sensor read functions poll.
 *          The flag is in ir.c — this callback just sets it.
 *
 * @param  hadc  Pointer to the ADC handle that triggered the callback.
 */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
    {
        ir_dma_complete_callback();
    }
}

/* =========================================================================
 * PERIPHERAL INITIALISATION FUNCTIONS
 * All static — only called from main() during startup.
 * Settings must exactly match pins.h and config.h.
 * ======================================================================= */

/**
 * @brief  Configure the system clock to 100 MHz via PLL.
 *
 * @details HSE 25 MHz external crystal → PLL → SYSCLK = 100 MHz.
 *          APB1 = 50 MHz (× 2 for timers = 100 MHz).
 *          APB2 = 100 MHz (× 1 for timers = 100 MHz).
 *          Flash latency = 3 wait states (required at 100 MHz, 3.3 V).
 */
static void system_clock_config(void)
{
    RCC_OscInitTypeDef       osc  = {0};
    RCC_ClkInitTypeDef       clk  = {0};

    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    /* HSE 25 MHz → PLL → 100 MHz */
    osc.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    osc.HSEState       = RCC_HSE_ON;
    osc.PLL.PLLState   = RCC_PLL_ON;
    osc.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    osc.PLL.PLLM       = 25U;   /* VCO input = 25/25 = 1 MHz            */
    osc.PLL.PLLN       = 200U;  /* VCO output = 1 × 200 = 200 MHz       */
    osc.PLL.PLLP       = RCC_PLLP_DIV2;   /* SYSCLK = 200/2 = 100 MHz  */
    osc.PLL.PLLQ       = 4U;    /* USB 48 MHz = 200/4 (not used here)   */

    if (HAL_RCC_OscConfig(&osc) != HAL_OK)
    {
        /* Clock config failure is unrecoverable */
        while (1) {}
    }

    clk.ClockType      = RCC_CLOCKTYPE_HCLK   | RCC_CLOCKTYPE_SYSCLK
                       | RCC_CLOCKTYPE_PCLK1  | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;    /* HCLK  = 100 MHz        */
    clk.APB1CLKDivider = RCC_HCLK_DIV2;      /* APB1  =  50 MHz        */
    clk.APB2CLKDivider = RCC_HCLK_DIV1;      /* APB2  = 100 MHz        */

    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_3) != HAL_OK)
    {
        while (1) {}
    }
}

/**
 * @brief  Initialise all GPIO pins as defined in pins.h.
 *
 * @details Configures:
 *            Output push-pull  : motor direction, emitters, STBY
 *            Input pull-up     : DIP switches, run button
 *            Input, no pull    : MPU6500_INT (PC13)
 *            Analog (no pull)  : ADC receiver pins PA2–PA7, PB0
 *            Alternate function: handled inside each timer/I2C init below
 *
 *          No onboard LED or buzzer on this board revision — both were
 *          dropped when PC13 was reassigned to MPU6500_INT.
 */
static void gpio_init(void)
{
    GPIO_InitTypeDef gpio = {0};

    /* Enable all GPIO port clocks */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* ── Output push-pull — motor direction */
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;

    gpio.Pin   = MOTOR_L_IN1_PIN | MOTOR_L_IN2_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);   /* PB12, PB13 — left motor dir       */

    gpio.Pin   = MOTOR_R_IN1_PIN | MOTOR_R_IN2_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);   /* PB14, PB15 — right motor dir      */

    /* ── Motor standby PB7 */
    gpio.Pin = MOTOR_STBY_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);
    MOTOR_DISABLE();               /* Safe default — motors off          */

    /* ── IR emitters (6 independent pins) */
    gpio.Pin = IR_EMIT_R_ANGLE_PIN | IR_EMIT_L_ANGLE_PIN;
    HAL_GPIO_Init(GPIOA, &gpio);   /* PA10, PA11 */

    gpio.Pin = IR_EMIT_RF_PIN;
    HAL_GPIO_Init(GPIOA, &gpio);   /* PA15 — freed by SWD-only debug     */

    gpio.Pin = IR_EMIT_LF_PIN | IR_EMIT_R_SIDE_PIN | IR_EMIT_L_SIDE_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);   /* PB3, PB2, PB1 */

    IR_ALL_EMITTERS_OFF();         /* Emitters off at startup            */

    /* ── Input pull-up — DIP switches */
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_PULLUP;

    gpio.Pin = DIP1_PIN;
    HAL_GPIO_Init(GPIOA, &gpio);   /* PA12 */

    gpio.Pin = DIP2_PIN | DIP3_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);   /* PB6, PB10 */

    gpio.Pin = DIP4_PIN;
    HAL_GPIO_Init(GPIOC, &gpio);   /* PC14 */

    /* ── Run button PC15 */
    gpio.Pin = BTN_PIN;
    HAL_GPIO_Init(GPIOC, &gpio);   /* PC15 */

    /* ── MPU6500 interrupt PC13 — input, no pull (push-pull source) */
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_NOPULL;
    gpio.Pin  = IMU_INT_PIN;
    HAL_GPIO_Init(GPIOC, &gpio);   /* PC13 */

    /* ── Analog — ADC receiver pins (no pull, no speed needed) */
    gpio.Mode  = GPIO_MODE_ANALOG;
    gpio.Pull  = GPIO_NOPULL;

    /* PA2–PA7: 6 IR receivers */
    gpio.Pin   = GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4
               | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7;
    HAL_GPIO_Init(GPIOA, &gpio);

    /* PB0: battery voltage divider */
    gpio.Pin   = BATT_ADC_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);
}

/**
 * @brief  Initialise DMA controller for ADC1 circular scan.
 *
 * @details Must be called BEFORE adc1_ir_battery_init().
 *          DMA2 Stream 0 Channel 0 is the ADC1 DMA request stream.
 */
static void dma_init(void)
{
    __HAL_RCC_DMA2_CLK_ENABLE();

    hdma_adc1.Instance                 = DMA2_Stream0;
    hdma_adc1.Init.Channel             = DMA_CHANNEL_0;
    hdma_adc1.Init.Direction           = DMA_PERIPH_TO_MEMORY;
    hdma_adc1.Init.PeriphInc           = DMA_PINC_DISABLE;
    hdma_adc1.Init.MemInc              = DMA_MINC_ENABLE;
    hdma_adc1.Init.PeriphDataAlignment = DMA_PDATAALIGN_HALFWORD;
    hdma_adc1.Init.MemDataAlignment    = DMA_MDATAALIGN_HALFWORD;
    hdma_adc1.Init.Mode                = DMA_CIRCULAR;
    hdma_adc1.Init.Priority            = DMA_PRIORITY_HIGH;
    hdma_adc1.Init.FIFOMode            = DMA_FIFOMODE_DISABLE;

    (void)HAL_DMA_Init(&hdma_adc1);
    __HAL_LINKDMA(&hadc1, DMA_Handle, hdma_adc1);

    /* DMA2 Stream 0 IRQ — priority below control loop (TIM5 = 1) */
    HAL_NVIC_SetPriority(DMA2_Stream0_IRQn, 2U, 0U);
    HAL_NVIC_EnableIRQ(DMA2_Stream0_IRQn);
}

/**
 * @brief  Initialise TIM1 for 20 kHz PWM on CH1 (PA8) and CH2 (PA9).
 *
 * @details PSC = 0, ARR = 4999 → 100 MHz / 5000 = 20 kHz.
 *          Both channels use PWM Mode 1.
 *          Preload enabled — duty updates take effect at next PWM period.
 *          Output compare preload prevents glitches during duty changes.
 */
static void tim1_pwm_init(void)
{
    GPIO_InitTypeDef       gpio = {0};
    TIM_OC_InitTypeDef     oc   = {0};
    TIM_MasterConfigTypeDef mc  = {0};

    __HAL_RCC_TIM1_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* PA8 → TIM1_CH1, PA9 → TIM1_CH2  (AF01) */
    gpio.Pin       = MOTOR_L_PWM_PIN | MOTOR_R_PWM_PIN;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_NOPULL;
    gpio.Speed     = GPIO_SPEED_FREQ_HIGH;
    gpio.Alternate = MOTOR_L_PWM_AF;   /* GPIO_AF1_TIM1 */
    HAL_GPIO_Init(MOTOR_L_PWM_PORT, &gpio);

    /* Timer base */
    htim1.Instance               = TIM1;
    htim1.Init.Prescaler         = MOTOR_TIM_PRESCALER;  /* 0 */
    htim1.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim1.Init.Period            = MOTOR_TIM_PERIOD;     /* 4999 */
    htim1.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim1.Init.RepetitionCounter = 0U;
    htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
    (void)HAL_TIM_PWM_Init(&htim1);

    mc.MasterOutputTrigger = TIM_TRGO_RESET;
    mc.MasterSlaveMode     = TIM_MASTERSLAVEMODE_DISABLE;
    (void)HAL_TIMEx_MasterConfigSynchronization(&htim1, &mc);

    /* Both channels: PWM Mode 1, preload enabled, start at 0 % */
    oc.OCMode       = TIM_OCMODE_PWM1;
    oc.Pulse        = 0U;
    oc.OCPolarity   = TIM_OCPOLARITY_HIGH;
    oc.OCFastMode   = TIM_OCFAST_DISABLE;
    oc.OCNPolarity  = TIM_OCNPOLARITY_HIGH;
    oc.OCIdleState  = TIM_OCIDLESTATE_RESET;
    oc.OCNIdleState = TIM_OCNIDLESTATE_RESET;

    (void)HAL_TIM_PWM_ConfigChannel(&htim1, &oc, TIM_CHANNEL_1);
    (void)HAL_TIM_PWM_ConfigChannel(&htim1, &oc, TIM_CHANNEL_2);

    /* Start both channels — duty = 0 so motors stay still */
    (void)HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
    (void)HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_2);
}

/**
 * @brief  Initialise TIM2 in encoder mode for the left wheel (32-bit).
 *
 * @details PA0 → TIM2_CH1, PA1 → TIM2_CH2.  Period = 0xFFFFFFFF
 *          (full 32-bit count range — no overflow handling needed).
 *          Both edges of both channels counted: ×4 quadrature.
 */
static void tim2_encoder_init(void)
{
    GPIO_InitTypeDef       gpio = {0};
    TIM_Encoder_InitTypeDef enc = {0};

    __HAL_RCC_TIM2_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* PA0 TIM2_CH1, PA1 TIM2_CH2 — AF01 */
    gpio.Pin       = ENC_L_A_PIN | ENC_L_B_PIN;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_PULLUP;   /* Pull-up prevents float on open encoder */
    gpio.Speed     = GPIO_SPEED_FREQ_LOW;
    gpio.Alternate = ENC_L_A_AF;   /* GPIO_AF1_TIM2 */
    HAL_GPIO_Init(ENC_L_A_PORT, &gpio);

    htim2.Instance               = TIM2;
    htim2.Init.Prescaler         = 0U;
    htim2.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim2.Init.Period            = 0xFFFFFFFFUL;   /* 32-bit full range */
    htim2.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;

    enc.EncoderMode   = TIM_ENCODERMODE_TI12;   /* count both edges */
    enc.IC1Polarity   = TIM_ICPOLARITY_RISING;
    enc.IC1Selection  = TIM_ICSELECTION_DIRECTTI;
    enc.IC1Prescaler  = TIM_ICPSC_DIV1;
    enc.IC1Filter     = 0x04U;   /* 4-cycle input filter (debounce)     */
    enc.IC2Polarity   = TIM_ICPOLARITY_RISING;
    enc.IC2Selection  = TIM_ICSELECTION_DIRECTTI;
    enc.IC2Prescaler  = TIM_ICPSC_DIV1;
    enc.IC2Filter     = 0x04U;

    (void)HAL_TIM_Encoder_Init(&htim2, &enc);
    (void)HAL_TIM_Encoder_Start(&htim2, TIM_CHANNEL_ALL);
}

/**
 * @brief  Initialise TIM3 in encoder mode for the right wheel (16-bit).
 *
 * @details PB4 → TIM3_CH1, PB5 → TIM3_CH2.  Period = 0xFFFF.
 *          TIM3 update IRQ enabled so encoders.c can extend to 32-bit
 *          by tracking overflow/underflow events.
 *          NVIC priority 3 (below control loop priority 1).
 */
static void tim3_encoder_init(void)
{
    GPIO_InitTypeDef       gpio = {0};
    TIM_Encoder_InitTypeDef enc = {0};

    __HAL_RCC_TIM3_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* PB4 TIM3_CH1, PB5 TIM3_CH2 — AF02 */
    gpio.Pin       = ENC_R_A_PIN | ENC_R_B_PIN;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_PULLUP;
    gpio.Speed     = GPIO_SPEED_FREQ_LOW;
    gpio.Alternate = ENC_R_A_AF;   /* GPIO_AF2_TIM3 */
    HAL_GPIO_Init(ENC_R_A_PORT, &gpio);

    htim3.Instance               = TIM3;
    htim3.Init.Prescaler         = 0U;
    htim3.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim3.Init.Period            = ENC_R_MAX_COUNT;   /* 0xFFFF */
    htim3.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim3.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;

    enc.EncoderMode   = TIM_ENCODERMODE_TI12;
    enc.IC1Polarity   = TIM_ICPOLARITY_RISING;
    enc.IC1Selection  = TIM_ICSELECTION_DIRECTTI;
    enc.IC1Prescaler  = TIM_ICPSC_DIV1;
    enc.IC1Filter     = 0x04U;
    enc.IC2Polarity   = TIM_ICPOLARITY_RISING;
    enc.IC2Selection  = TIM_ICSELECTION_DIRECTTI;
    enc.IC2Prescaler  = TIM_ICPSC_DIV1;
    enc.IC2Filter     = 0x04U;

    (void)HAL_TIM_Encoder_Init(&htim3, &enc);
    (void)HAL_TIM_Encoder_Start(&htim3, TIM_CHANNEL_ALL);

    /* Enable update interrupt for overflow extension */
    HAL_NVIC_SetPriority(TIM3_IRQn, 3U, 0U);
    HAL_NVIC_EnableIRQ(TIM3_IRQn);
    __HAL_TIM_ENABLE_IT(&htim3, TIM_IT_UPDATE);
}

/**
 * @brief  Initialise TIM5 as a 1 kHz interrupt source for the control loop.
 *
 * @details PSC = 99  → tick rate = 100 MHz / 100 = 1 MHz
 *          ARR = 999 → IRQ rate  = 1 MHz / 1000  = 1 kHz
 *          NVIC priority 1 (highest after SysTick which is 0).
 *          Timer is NOT started here — started in main() after all
 *          modules are ready, to prevent ISR firing during init.
 */
static void tim5_ctrl_loop_init(void)
{
    __HAL_RCC_TIM5_CLK_ENABLE();

    htim5.Instance               = CTRL_TIM_INSTANCE;   /* TIM5 */
    htim5.Init.Prescaler         = CTRL_TIM_PSC;        /* 99   */
    htim5.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim5.Init.Period            = CTRL_TIM_ARR;        /* 999  */
    htim5.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim5.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;

    (void)HAL_TIM_Base_Init(&htim5);

    HAL_NVIC_SetPriority(TIM5_IRQn, CTRL_TIM_PRIORITY, 0U);
    HAL_NVIC_EnableIRQ(TIM5_IRQn);

    /* Start immediately after modules_init() completes */
    (void)HAL_TIM_Base_Start_IT(&htim5);
}

/**
 * @brief  Initialise ADC1 with 7-channel DMA circular scan.
 *
 * @details Rank order (must match IR_IDX_* in pins.h):
 *            Rank 1  PA2 IN2  Right Side  receiver
 *            Rank 2  PA3 IN3  Left  Side  receiver
 *            Rank 3  PA4 IN4  Right Front receiver
 *            Rank 4  PA5 IN5  Left  Front receiver
 *            Rank 5  PA6 IN6  Right Angle receiver
 *            Rank 6  PA7 IN7  Left  Angle receiver
 *            Rank 7  PB0 IN8  Battery voltage divider
 *
 *          Sample time: 84 cycles per channel.
 *          Conversion is triggered by software inside ir_update().
 *          DMA circular mode — buffer is always up-to-date.
 */
static void adc1_ir_battery_init(void)
{
    ADC_ChannelConfTypeDef ch = {0};

    __HAL_RCC_ADC1_CLK_ENABLE();

    hadc1.Instance                   = IR_ADC_INSTANCE;   /* ADC1 */
    hadc1.Init.ClockPrescaler        = ADC_CLOCK_SYNC_PCLK_DIV4;
    hadc1.Init.Resolution            = ADC_RESOLUTION_12B;
    hadc1.Init.ScanConvMode          = ENABLE;
    hadc1.Init.ContinuousConvMode    = DISABLE;   /* Software-triggered */
    hadc1.Init.DiscontinuousConvMode = DISABLE;
    hadc1.Init.ExternalTrigConv      = ADC_SOFTWARE_START;
    hadc1.Init.ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc1.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
    hadc1.Init.NbrOfConversion       = IR_ADC_BUF_LEN;   /* 7 */
    hadc1.Init.DMAContinuousRequests = ENABLE;
    hadc1.Init.EOCSelection          = ADC_EOC_SEQ_CONV;

    (void)HAL_ADC_Init(&hadc1);

    /* Configure each rank */
    const ADC_ChannelConfTypeDef channels[IR_ADC_BUF_LEN] = {
        { .Channel = IR_RECV_RS_ADC_CH,    .Rank = IR_RECV_RS_ADC_RANK,    .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_LS_ADC_CH,    .Rank = IR_RECV_LS_ADC_RANK,    .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_RF_ADC_CH,    .Rank = IR_RECV_RF_ADC_RANK,    .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_LF_ADC_CH,    .Rank = IR_RECV_LF_ADC_RANK,    .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_R_ANG_ADC_CH, .Rank = IR_RECV_R_ANG_ADC_RANK, .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_L_ANG_ADC_CH, .Rank = IR_RECV_L_ANG_ADC_RANK, .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = BATT_ADC_CH,          .Rank = BATT_ADC_RANK,          .SamplingTime = ADC_SAMPLETIME_84CYCLES },
    };

    for (uint8_t i = 0U; i < IR_ADC_BUF_LEN; i++)
    {
        ch = channels[i];
        (void)HAL_ADC_ConfigChannel(&hadc1, &ch);
    }
}

/**
 * @brief  Initialise I2C1 at 400 kHz for MPU6500 and SSD1306 OLED.
 *
 * @details PB8 → I2C1_SCL (AF04), PB9 → I2C1_SDA (AF04).
 *          Both pins require external 4.7 kΩ pull-up resistors to 3.3 V.
 *          The STM32F411 I2C_CR2 timing register value for 400 kHz
 *          at 50 MHz APB1 clock: 0x0C2177.  (From AN4235 Table 8.)
 */
static void i2c1_init(void)
{
    GPIO_InitTypeDef gpio = {0};

    __HAL_RCC_I2C1_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* PB8 SCL, PB9 SDA — open-drain, AF04 */
    gpio.Pin       = IMU_SCL_PIN | IMU_SDA_PIN;
    gpio.Mode      = GPIO_MODE_AF_OD;
    gpio.Pull      = GPIO_NOPULL;   /* External pull-ups on PCB          */
    gpio.Speed     = GPIO_SPEED_FREQ_HIGH;
    gpio.Alternate = IMU_SCL_AF;    /* GPIO_AF4_I2C1 */
    HAL_GPIO_Init(IMU_SCL_PORT, &gpio);

    hi2c1.Instance             = IMU_I2C_INSTANCE;   /* I2C1 */
    hi2c1.Init.ClockSpeed      = IMU_I2C_SPEED;      /* 400 000 Hz */
    hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1     = 0U;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;

    (void)HAL_I2C_Init(&hi2c1);
}

/* =========================================================================
 * HARD FAULT HANDLER
 * ======================================================================= */

/**
 * @brief  HardFault exception handler.
 *
 * @details Disables motors immediately, then halts forever — requires a
 *          hardware reset to recover. No onboard LED is available on
 *          this board revision to signal the fault visually; connect
 *          ST-Link and set a breakpoint here to inspect the stack frame
 *          and identify the fault address.
 */
void HardFault_Handler(void)
{
    /* Disable motors — most important thing to do immediately */
    MOTOR_DISABLE();
    MOTOR_L_COAST();
    MOTOR_R_COAST();
    IR_ALL_EMITTERS_OFF();

    while (1)
    {
        /* Busy-wait — HAL_Delay (SysTick) may not work in HardFault  */
        for (volatile uint32_t d = 0U; d < 2000000UL; d++) {}
    }
}
