/**
 * @file    main.c
 * @brief   MicroMaze 3 — STM32F411CEU6 Black Pill
 *          Firmware entry point and peripheral initialisation.
 *
 * @details Responsibilities of this file:
 *            1. HAL and system clock initialisation.
 *            2. All STM32 peripheral configuration (generated by CubeMX
 *               then hand-edited to match pins.h exactly).
 *            3. Module bring-up in dependency order.
 *            4. DIP switch read → mode dispatch.
 *            5. HAL callback routing (timer IRQs → correct modules).
 *
 *          PERIPHERAL CONFIGURATION SUMMARY
 *          ─────────────────────────────────
 *          TIM1  PWM CH1+CH2  PA8/PA9      Motor PWM 20 kHz
 *          TIM2  Encoder      PA0/PA1      Left  encoder (32-bit)
 *          TIM4  Encoder      PB6/PB7      Right encoder (16-bit + OVF)
 *          TIM5  Base timer   —            1 kHz control loop IRQ
 *          ADC1  DMA scan     PA2–PA7,PB0  6 IR receivers + battery
 *          I2C1  400 kHz      PB8/PB9      MPU6500 + SSD1306 OLED
 *          UART1 115200 baud  —            Debug output (USB-serial)
 *
 *          CUBEMX SETTINGS REQUIRED
 *          ─────────────────────────
 *          System Core → SYS → Debug: Serial Wire   ← frees PA15, PB3
 *          TIM1  → PWM Gen CH1+CH2, PSC=0, ARR=4999
 *          TIM2  → Encoder Mode TI1+TI2, Period=0xFFFFFFFF
 *          TIM4  → Encoder Mode TI1+TI2, Period=0xFFFF, NVIC enabled
 *          TIM5  → Timer interrupt, PSC=99, ARR=999, NVIC priority 1
 *          ADC1  → Scan+DMA, 7 ranks, software trigger, circular DMA
 *          I2C1  → Fast mode 400 kHz
 *          UART1 → Async 115200 8N1 (or use USB CDC — see logger.c)
 *
 * @author  VDawn
 * @date    2026
 */

#include "main.h"

/* ── Module includes (dependency order — lower layers first) ─────────── */
#include "config.h"
#include "pins.h"
#include "types.h"
#include "error.h"

/* Utils */
#include "utils.h"

/* Drivers */
#include "motors.h"
#include "encoders.h"
#include "ir.h"
#include "imu.h"
#include "battery.h"
#include "buzzer.h"
#include "oled.h"
#include "buttons.h"
#include "flash_storage.h"

/* Control */
#include "pid.h"
#include "motion.h"
#include "turn.h"
#include "trajectory.h"
#include "wall_follow.h"

/* Navigation */
#include "maze.h"
#include "floodfill.h"
#include "explorer.h"
#include "speedrun.h"

/* Calibration */
#include "calibration.h"
#include "sensor_cal.h"
#include "gyro_cal.h"

/* System */
#include "scheduler.h"
#include "modes.h"
#include "diagnostics.h"
#include "logger.h"

/* =========================================================================
 * HAL PERIPHERAL HANDLES
 * Declared here — extern'd in main.h so every module can access them.
 * CubeMX generates these declarations; they are listed here explicitly
 * so the handle-to-peripheral mapping is always visible in one place.
 * ======================================================================= */

TIM_HandleTypeDef  htim1;   /**< Motor PWM  — TIM1 CH1 PA8, CH2 PA9      */
TIM_HandleTypeDef  htim2;   /**< Left  encoder — TIM2 PA0/PA1 (32-bit)   */
TIM_HandleTypeDef  htim4;   /**< Right encoder — TIM4 PB6/PB7 (16-bit)   */
TIM_HandleTypeDef  htim5;   /**< Control loop 1 kHz — TIM5                */
ADC_HandleTypeDef  hadc1;   /**< IR + battery ADC scan — ADC1             */
DMA_HandleTypeDef  hdma_adc1; /**< DMA for ADC1 circular scan             */
I2C_HandleTypeDef  hi2c1;   /**< MPU6500 + OLED — I2C1 PB8/PB9           */
UART_HandleTypeDef huart1;  /**< Debug UART1                              */

/* =========================================================================
 * PRIVATE FUNCTION PROTOTYPES
 * All init helpers are static — they are internal to this file.
 * ======================================================================= */

static void system_clock_config(void);
static void gpio_init(void);
static void dma_init(void);
static void tim1_pwm_init(void);
static void tim2_encoder_init(void);
static void tim4_encoder_init(void);
static void tim5_ctrl_loop_init(void);
static void adc1_ir_battery_init(void);
static void i2c1_init(void);
static void uart1_init(void);

static MmResult_t modules_init(void);
static void       run_selected_mode(uint8_t mode);
static void       fatal_error_handler(MmResult_t err);

/* =========================================================================
 * MAIN ENTRY POINT
 * ======================================================================= */

/**
 * @brief  Firmware entry point.
 *
 * @details Sequence:
 *   1.  HAL_Init          — SysTick, interrupt priority grouping.
 *   2.  system_clock_config — 100 MHz from HSE 25 MHz PLL.
 *   3.  utils_init        — DWT microsecond counter.
 *   4.  Peripheral init   — GPIO, DMA, timers, ADC, I2C, UART.
 *   5.  modules_init      — drivers, control, navigation, system layers.
 *   6.  DIP switch read   — determines which mode to run.
 *   7.  run_selected_mode — blocking mode dispatcher, never returns.
 *
 * @return int  Never reached (embedded infinite loop).
 */
int main(void)
{
    MmResult_t result;

    /* ── 1. HAL initialisation ─────────────────────────────────────────
     *  Configures SysTick for 1 ms HAL_GetTick(), sets interrupt
     *  priority grouping to NVIC_PRIORITYGROUP_4 (4 bits preemption,
     *  0 bits sub-priority).
     * ────────────────────────────────────────────────────────────────── */
    HAL_Init();

    /* ── 2. System clock: HSE 25 MHz → PLL → 100 MHz ───────────────── */
    system_clock_config();

    /* ── 3. DWT microsecond counter (must be before any delay_us call) */
    utils_init();

    /* ── 4. Peripheral initialisation (order matters) ──────────────── */
    gpio_init();        /* All GPIO directions, speeds, pull-ups        */
    dma_init();         /* DMA controller clocks — must precede ADC     */
    tim1_pwm_init();    /* Motor PWM channels — outputs start at 0 %   */
    tim2_encoder_init();/* Left  encoder (32-bit, PA0/PA1)              */
    tim4_encoder_init();/* Right encoder (16-bit, PB6/PB7) + NVIC      */
    adc1_ir_battery_init(); /* 7-channel DMA circular scan             */
    i2c1_init();        /* MPU6500 + OLED at 400 kHz                   */
    uart1_init();       /* Debug output 115200 baud                    */

    /* ── 5. Logger online — all subsequent output goes to UART ─────── */
    logger_init(&huart1);
    LOG_INFO("MicroMaze 3 firmware v%u.%u.%u booting",
             FW_VERSION_MAJOR, FW_VERSION_MINOR, FW_VERSION_PATCH);

    /* ── 6. Module initialisation ───────────────────────────────────── */
    result = modules_init();
    if (result != MM_OK)
    {
        fatal_error_handler(result);
        /* Never returns */
    }

    /* ── 7. Start control loop timer (1 kHz) ───────────────────────── */
    /* Must start AFTER all modules are initialised because the ISR
     * immediately calls motion_1khz_tick() which touches driver state. */
    tim5_ctrl_loop_init();
    LOG_INFO("Control loop started at %u Hz", CTRL_LOOP_HZ);

    /* ── 8. Read DIP switches → select operating mode ──────────────── */
    /* Short delay lets switch inputs settle after power-on.            */
    HAL_Delay(10U);
    uint8_t mode = READ_DIP_SWITCHES();

    LOG_INFO("DIP switches: %u  (SW3=%u SW2=%u SW1=%u SW0=%u)",
             mode,
             (mode >> 3U) & 1U, (mode >> 2U) & 1U,
             (mode >> 1U) & 1U,  mode        & 1U);

    /* Announce mode on OLED and buzzer */
    oled_show_mode(mode);
    buzzer_boot();

    /* ── 9. Blocking mode dispatcher ───────────────────────────────── */
    run_selected_mode(mode);

    /* Should never reach here — every mode runs an infinite loop or
     * blocks until its task is complete then halts.                    */
    LOG_ERROR("run_selected_mode returned unexpectedly (mode %u)", mode);
    fatal_error_handler(MM_ERR_GENERAL);

    /* Suppress compiler "control reaches end of non-void function"    */
    return 0;
}

/* =========================================================================
 * MODULE INITIALISATION
 * ======================================================================= */

/**
 * @brief  Initialise all firmware modules in dependency order.
 *
 * @details Each module's init function returns MM_OK on success or an
 *          error code on failure.  Initialisation stops at the first
 *          failure and the error code is returned to main().
 *
 *          Order: Utils → Drivers → Calibration load → Control → Navigation
 *
 * @return MM_OK if all modules initialised successfully.
 * @return Error code from the first module that failed.
 */
static MmResult_t modules_init(void)
{
    MmResult_t result;

    LOG_INFO("Initialising modules...");

    /* ── Drivers layer ─────────────────────────────────────────────── */

    buzzer_init();
    LED_OFF();

    motors_init();          /* PWM channels, direction pins, STBY LOW   */
    LOG_DEBUG("motors OK");

    encoders_init();        /* TIM2 + TIM4 encoder start                */
    LOG_DEBUG("encoders OK");

    result = ir_init();     /* ADC1 DMA start, load cal from Flash      */
    if (result != MM_OK)
    {
        LOG_ERROR("IR init failed: %d", result);
        return result;
    }
    LOG_DEBUG("IR sensors OK");

    result = imu_init(&hi2c1);
    if (result != MM_OK)
    {
        LOG_ERROR("IMU init failed: %d — check I2C wiring PB8/PB9", result);
        oled_show_error("IMU FAIL");
        buzzer_error();
        return result;
    }
    LOG_INFO("IMU WHO_AM_I = 0x%02X (expected 0x%02X)",
             imu_who_am_i(), MPU6500_WHO_AM_I_VAL);

    battery_init(&hadc1);
    LOG_DEBUG("battery monitor OK  %.2f V", battery_voltage());

    oled_init(&hi2c1);
    oled_show_boot();
    LOG_DEBUG("OLED OK");

    buttons_init();
    LOG_DEBUG("buttons OK");

    /* ── Flash: load calibration data ─────────────────────────────── */
    result = flash_storage_load_calibration();
    if (result == MM_OK)
    {
        LOG_INFO("Calibration loaded from Flash (magic valid)");
    }
    else
    {
        LOG_WARN("No valid calibration in Flash — using defaults");
        LOG_WARN("Run Mode %u (IR calibration) before first race",
                 MODE_IR_CALIBRATE);
    }

    /* ── IMU calibration (gyro zero-rate offset) ───────────────────── */
    LOG_INFO("Calibrating gyro — keep robot still for %u ms...",
             GYRO_CAL_SAMPLES);
    oled_show_message("GYRO CAL...", "KEEP STILL");

    result = gyro_cal_run();
    if (result != MM_OK)
    {
        LOG_ERROR("Gyro calibration failed: %d", result);
        return result;
    }
    LOG_INFO("Gyro calibrated  offset = %.4f deg/s", gyro_cal_get_offset());

    /* ── Control layer ─────────────────────────────────────────────── */
    motion_init();
    turn_init();
    trajectory_init();
    wall_follow_init();
    LOG_DEBUG("control layer OK");

    /* ── Navigation layer ──────────────────────────────────────────── */
    maze_init();
    floodfill_init();
    explorer_init();
    speedrun_init();
    LOG_DEBUG("navigation layer OK");

    /* ── System layer ──────────────────────────────────────────────── */
    scheduler_init();
    diagnostics_init();
    LOG_DEBUG("system layer OK");

    LOG_INFO("All modules OK  battery=%.2fV", battery_voltage());
    oled_show_boot_complete();
    buzzer_beep(BUZZ_START_MS);
    LED_ON();

    return MM_OK;
}

/* =========================================================================
 * MODE DISPATCHER
 * ======================================================================= */

/**
 * @brief  Dispatch to the function for the DIP-selected operating mode.
 *
 * @details This function never returns under normal operation.  Each
 *          mode function either loops indefinitely or performs its task
 *          and then halts in an idle loop.
 *
 * @param  mode  DIP switch value 0–15 (from READ_DIP_SWITCHES()).
 */
static void run_selected_mode(uint8_t mode)
{
    LOG_INFO(">>> Running mode %u <<<", mode);

    switch (mode)
    {
        case MODE_MONITOR:
            modes_run_monitor();
            break;

        case MODE_IR_CALIBRATE:
            modes_run_ir_calibrate();
            break;

        case MODE_MOTOR_TEST:
            modes_run_motor_test();
            break;

        case MODE_STRAIGHT_TEST:
            modes_run_straight_test();
            break;

        case MODE_TURN_TEST:
            modes_run_turn_test();
            break;

        case MODE_WALL_FOLLOWER:
            modes_run_wall_follower();
            break;

        case MODE_SEARCH_RUN:
            modes_run_search();
            break;

        case MODE_SPEED_RUN_1:
            modes_run_speed(SPD_RUN1);
            break;

        case MODE_SPEED_RUN_2:
            modes_run_speed(SPD_RUN2);
            break;

        case MODE_SPEED_RUN_3:
            modes_run_speed(SPD_RUN3);
            break;

        case MODE_AUTO_QUALIFIER:
            modes_run_auto_qualifier();
            break;

        case MODE_GYRO_DEBUG:
            modes_run_gyro_debug();
            break;

        case MODE_PRINT_MAZE:
            modes_run_print_maze();
            break;

        case MODE_BATTERY_CHECK:
            modes_run_battery_check();
            break;

        case MODE_STARTUP_TEST:
            modes_run_startup_test();
            break;

        case MODE_RESERVED:
        default:
            LOG_WARN("Mode %u is reserved or undefined — entering monitor", mode);
            modes_run_monitor();
            break;
    }

    /* All mode functions should loop internally.  If any returns,
     * halt safely with motors off and log the event.                   */
    motors_disable();
    LOG_WARN("Mode %u function returned — motors disabled, halting", mode);

    while (1)
    {
        LED_TOGGLE();
        HAL_Delay(500U);
    }
}

/* =========================================================================
 * FATAL ERROR HANDLER
 * ======================================================================= */

/**
 * @brief  Called when a module fails to initialise.
 *
 * @details Disables motors, displays the error code on the OLED,
 *          logs the error, and blinks the LED in a pattern that encodes
 *          the error code for field debugging without a serial terminal.
 *          Never returns.
 *
 *          LED blink pattern: N long blinks where N = error code value.
 *
 * @param  err  Error code from the failing module (MmResult_t).
 */
static void fatal_error_handler(MmResult_t err)
{
    motors_disable();
    buzzer_error();

    LOG_ERROR("FATAL: init failed with error %d — halting", (int32_t)err);

    char msg[24];
    (void)snprintf(msg, sizeof(msg), "ERR %d", (int32_t)err);
    oled_show_error(msg);

    /* Blink pattern: rapid double-blink then pause, repeat forever     */
    while (1)
    {
        /* Rapid blink indicates fatal error */
        for (uint8_t i = 0U; i < 6U; i++)
        {
            LED_TOGGLE();
            HAL_Delay(100U);
        }
        HAL_Delay(800U);
    }
}

/* =========================================================================
 * HAL INTERRUPT CALLBACKS
 * These are called by the STM32 HAL from the appropriate IRQ handlers.
 * The IRQ handler names (TIM5_IRQHandler etc.) are in stm32f4xx_it.c
 * (generated by CubeMX) and call HAL_TIM_IRQHandler(&htim5) which then
 * calls HAL_TIM_PeriodElapsedCallback below.
 * ======================================================================= */

/**
 * @brief  HAL timer period-elapsed callback.
 *
 * @details Routes timer update events to the correct module:
 *            TIM5 → motion_1khz_tick()   (1 kHz control loop)
 *            TIM4 → encoders_tim4_ovf()  (right encoder overflow extend)
 *
 *          Keep this function as short as possible — it runs inside an ISR.
 *          Do not call HAL_Delay() or any blocking function here.
 *
 * @param  htim  Pointer to the timer handle that triggered the callback.
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM5)
    {
        /* 1 kHz control loop: sensors → gyro → PID → motor output      */
        motion_1khz_tick();
    }
    else if (htim->Instance == TIM4)
    {
        /* Extend 16-bit TIM4 right encoder to 32-bit using overflow cnt */
        encoders_tim4_ovf_irq();
    }
}

/**
 * @brief  HAL ADC conversion complete callback (DMA).
 *
 * @details Called when the ADC1 DMA circular buffer completes one full
 *          sweep of all 7 channels (6 IR receivers + battery).
 *          Sets a flag that the sensor read functions poll.
 *          The flag is in ir.c — this callback just sets it.
 *
 * @param  hadc  Pointer to the ADC handle that triggered the callback.
 */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1)
    {
        ir_dma_complete_callback();
    }
}

/* =========================================================================
 * PERIPHERAL INITIALISATION FUNCTIONS
 * All static — only called from main() during startup.
 * Settings must exactly match pins.h and config.h.
 * ======================================================================= */

/**
 * @brief  Configure the system clock to 100 MHz via PLL.
 *
 * @details HSE 25 MHz external crystal → PLL → SYSCLK = 100 MHz.
 *          APB1 = 50 MHz (× 2 for timers = 100 MHz).
 *          APB2 = 100 MHz (× 1 for timers = 100 MHz).
 *          Flash latency = 3 wait states (required at 100 MHz, 3.3 V).
 */
static void system_clock_config(void)
{
    RCC_OscInitTypeDef       osc  = {0};
    RCC_ClkInitTypeDef       clk  = {0};

    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    /* HSE 25 MHz → PLL → 100 MHz */
    osc.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    osc.HSEState       = RCC_HSE_ON;
    osc.PLL.PLLState   = RCC_PLL_ON;
    osc.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    osc.PLL.PLLM       = 25U;   /* VCO input = 25/25 = 1 MHz            */
    osc.PLL.PLLN       = 200U;  /* VCO output = 1 × 200 = 200 MHz       */
    osc.PLL.PLLP       = RCC_PLLP_DIV2;   /* SYSCLK = 200/2 = 100 MHz  */
    osc.PLL.PLLQ       = 4U;    /* USB 48 MHz = 200/4 (not used here)   */

    if (HAL_RCC_OscConfig(&osc) != HAL_OK)
    {
        /* Clock config failure is unrecoverable */
        while (1) {}
    }

    clk.ClockType      = RCC_CLOCKTYPE_HCLK   | RCC_CLOCKTYPE_SYSCLK
                       | RCC_CLOCKTYPE_PCLK1  | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;    /* HCLK  = 100 MHz        */
    clk.APB1CLKDivider = RCC_HCLK_DIV2;      /* APB1  =  50 MHz        */
    clk.APB2CLKDivider = RCC_HCLK_DIV1;      /* APB2  = 100 MHz        */

    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_3) != HAL_OK)
    {
        while (1) {}
    }
}

/**
 * @brief  Initialise all GPIO pins as defined in pins.h.
 *
 * @details Configures:
 *            Output push-pull  : motor direction, emitters, STBY, buzzer, LED
 *            Input pull-up     : DIP switches, run button
 *            Analog (no pull)  : ADC receiver pins PA2–PA7, PB0
 *            Alternate function: handled inside each timer/I2C init below
 */
static void gpio_init(void)
{
    GPIO_InitTypeDef gpio = {0};

    /* Enable all GPIO port clocks */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* ── Output push-pull — motor direction (PB11, PB12, PB13, PB14, PB15) */
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;

    gpio.Pin   = PIN_AIN1_PIN | PIN_AIN2_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);   /* PB2, PB3 left motor dir */

    gpio.Pin   = PIN_BIN1_PIN | PIN_BIN2_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);   /* PB12, PB11 right motor dir */

    /* ── Motor standby PB10 */
    gpio.Pin = PIN_STBY_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);
    MOTOR_DISABLE();               /* Safe default — motors off          */

    /* ── IR emitters (6 independent pins) */
    gpio.Pin = PIN_IR_EMIT_R_ANGLE_PIN | PIN_IR_EMIT_L_ANGLE_PIN;
    HAL_GPIO_Init(GPIOA, &gpio);   /* PA10, PA11 */

    gpio.Pin = PIN_IR_EMIT_RF_PIN;
    HAL_GPIO_Init(GPIOA, &gpio);   /* PA15 — freed by SWD-only debug     */

    gpio.Pin = PIN_IR_EMIT_LF_PIN | PIN_IR_EMIT_R_SIDE_PIN | PIN_IR_EMIT_L_SIDE_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);   /* PB3, PB4, PB5 */

    IR_ALL_EMITTERS_OFF();         /* Emitters off at startup            */

    /* ── Buzzer PB1 */
    gpio.Pin = BUZZER_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);
    BUZZER_OFF();

    /* ── Status LED PC13 */
    gpio.Pin = LED_PIN;
    HAL_GPIO_Init(GPIOC, &gpio);
    LED_OFF();

    /* ── Input pull-up — DIP switches */
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_PULLUP;

    gpio.Pin = DIP1_PIN;
    HAL_GPIO_Init(GPIOA, &gpio);   /* PA12 */

    gpio.Pin = DIP2_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);   /* PB2  */

    gpio.Pin = DIP3_PIN | DIP4_PIN;
    HAL_GPIO_Init(GPIOC, &gpio);   /* PC14, PC13 shared with LED         */

    /* ── Run button PC15 */
    gpio.Pin = BTN_PIN;
    HAL_GPIO_Init(GPIOC, &gpio);   /* PC15 */

    /* ── Analog — ADC receiver pins (no pull, no speed needed) */
    gpio.Mode  = GPIO_MODE_ANALOG;
    gpio.Pull  = GPIO_NOPULL;

    /* PA2–PA7: 6 IR receivers */
    gpio.Pin   = GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4
               | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7;
    HAL_GPIO_Init(GPIOA, &gpio);

    /* PB0: battery voltage divider */
    gpio.Pin   = BATT_ADC_PIN;
    HAL_GPIO_Init(GPIOB, &gpio);
}

/**
 * @brief  Initialise DMA controller for ADC1 circular scan.
 *
 * @details Must be called BEFORE adc1_ir_battery_init().
 *          DMA2 Stream 0 Channel 0 is the ADC1 DMA request stream.
 */
static void dma_init(void)
{
    __HAL_RCC_DMA2_CLK_ENABLE();

    hdma_adc1.Instance                 = DMA2_Stream0;
    hdma_adc1.Init.Channel             = DMA_CHANNEL_0;
    hdma_adc1.Init.Direction           = DMA_PERIPH_TO_MEMORY;
    hdma_adc1.Init.PeriphInc           = DMA_PINC_DISABLE;
    hdma_adc1.Init.MemInc              = DMA_MINC_ENABLE;
    hdma_adc1.Init.PeriphDataAlignment = DMA_PDATAALIGN_HALFWORD;
    hdma_adc1.Init.MemDataAlignment    = DMA_MDATAALIGN_HALFWORD;
    hdma_adc1.Init.Mode                = DMA_CIRCULAR;
    hdma_adc1.Init.Priority            = DMA_PRIORITY_HIGH;
    hdma_adc1.Init.FIFOMode            = DMA_FIFOMODE_DISABLE;

    (void)HAL_DMA_Init(&hdma_adc1);
    __HAL_LINKDMA(&hadc1, DMA_Handle, hdma_adc1);

    /* DMA2 Stream 0 IRQ — priority below control loop (TIM5 = 1) */
    HAL_NVIC_SetPriority(DMA2_Stream0_IRQn, 2U, 0U);
    HAL_NVIC_EnableIRQ(DMA2_Stream0_IRQn);
}

/**
 * @brief  Initialise TIM1 for 20 kHz PWM on CH1 (PA8) and CH2 (PA9).
 *
 * @details PSC = 0, ARR = 4999 → 100 MHz / 5000 = 20 kHz.
 *          Both channels use PWM Mode 1.
 *          Preload enabled — duty updates take effect at next PWM period.
 *          Output compare preload prevents glitches during duty changes.
 */
static void tim1_pwm_init(void)
{
    GPIO_InitTypeDef       gpio = {0};
    TIM_OC_InitTypeDef     oc   = {0};
    TIM_MasterConfigTypeDef mc  = {0};

    __HAL_RCC_TIM1_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* PA8 → TIM1_CH1, PA9 → TIM1_CH2  (AF01) */
    gpio.Pin       = MOTOR_L_PWM_PIN | MOTOR_R_PWM_PIN;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_NOPULL;
    gpio.Speed     = GPIO_SPEED_FREQ_HIGH;
    gpio.Alternate = MOTOR_L_PWM_AF;   /* GPIO_AF1_TIM1 */
    HAL_GPIO_Init(MOTOR_L_PWM_PORT, &gpio);

    /* Timer base */
    htim1.Instance               = TIM1;
    htim1.Init.Prescaler         = MOTOR_TIM_PRESCALER;  /* 0 */
    htim1.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim1.Init.Period            = MOTOR_TIM_PERIOD;     /* 4999 */
    htim1.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim1.Init.RepetitionCounter = 0U;
    htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
    (void)HAL_TIM_PWM_Init(&htim1);

    mc.MasterOutputTrigger = TIM_TRGO_RESET;
    mc.MasterSlaveMode     = TIM_MASTERSLAVEMODE_DISABLE;
    (void)HAL_TIMEx_MasterConfigSynchronization(&htim1, &mc);

    /* Both channels: PWM Mode 1, preload enabled, start at 0 % */
    oc.OCMode       = TIM_OCMODE_PWM1;
    oc.Pulse        = 0U;
    oc.OCPolarity   = TIM_OCPOLARITY_HIGH;
    oc.OCFastMode   = TIM_OCFAST_DISABLE;
    oc.OCNPolarity  = TIM_OCNPOLARITY_HIGH;
    oc.OCIdleState  = TIM_OCIDLESTATE_RESET;
    oc.OCNIdleState = TIM_OCNIDLESTATE_RESET;

    (void)HAL_TIM_PWM_ConfigChannel(&htim1, &oc, TIM_CHANNEL_1);
    (void)HAL_TIM_PWM_ConfigChannel(&htim1, &oc, TIM_CHANNEL_2);

    /* Start both channels — duty = 0 so motors stay still */
    (void)HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);
    (void)HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_2);
}

/**
 * @brief  Initialise TIM2 in encoder mode for the left wheel (32-bit).
 *
 * @details PA0 → TIM2_CH1, PA1 → TIM2_CH2.  Period = 0xFFFFFFFF
 *          (full 32-bit count range — no overflow handling needed).
 *          Both edges of both channels counted: ×4 quadrature.
 */
static void tim2_encoder_init(void)
{
    GPIO_InitTypeDef       gpio = {0};
    TIM_Encoder_InitTypeDef enc = {0};

    __HAL_RCC_TIM2_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* PA0 TIM2_CH1, PA1 TIM2_CH2 — AF01 */
    gpio.Pin       = ENC_L_A_PIN | ENC_L_B_PIN;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_PULLUP;   /* Pull-up prevents float on open encoder */
    gpio.Speed     = GPIO_SPEED_FREQ_LOW;
    gpio.Alternate = ENC_L_A_AF;   /* GPIO_AF1_TIM2 */
    HAL_GPIO_Init(ENC_L_A_PORT, &gpio);

    htim2.Instance               = TIM2;
    htim2.Init.Prescaler         = 0U;
    htim2.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim2.Init.Period            = 0xFFFFFFFFUL;   /* 32-bit full range */
    htim2.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;

    enc.EncoderMode   = TIM_ENCODERMODE_TI12;   /* count both edges */
    enc.IC1Polarity   = TIM_ICPOLARITY_RISING;
    enc.IC1Selection  = TIM_ICSELECTION_DIRECTTI;
    enc.IC1Prescaler  = TIM_ICPSC_DIV1;
    enc.IC1Filter     = 0x04U;   /* 4-cycle input filter (debounce)     */
    enc.IC2Polarity   = TIM_ICPOLARITY_RISING;
    enc.IC2Selection  = TIM_ICSELECTION_DIRECTTI;
    enc.IC2Prescaler  = TIM_ICPSC_DIV1;
    enc.IC2Filter     = 0x04U;

    (void)HAL_TIM_Encoder_Init(&htim2, &enc);
    (void)HAL_TIM_Encoder_Start(&htim2, TIM_CHANNEL_ALL);
}

/**
 * @brief  Initialise TIM4 in encoder mode for the right wheel (16-bit).
 *
 * @details PB6 → TIM4_CH1, PB7 → TIM4_CH2.  Period = 0xFFFF.
 *          TIM4 update IRQ enabled so encoders.c can extend to 32-bit
 *          by tracking overflow/underflow events.
 *          NVIC priority 3 (below control loop priority 1).
 */
static void tim4_encoder_init(void)
{
    GPIO_InitTypeDef       gpio = {0};
    TIM_Encoder_InitTypeDef enc = {0};

    __HAL_RCC_TIM4_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* PB6 TIM4_CH1, PB7 TIM4_CH2 — AF02 */
    gpio.Pin       = ENC_R_A_PIN | ENC_R_B_PIN;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_PULLUP;
    gpio.Speed     = GPIO_SPEED_FREQ_LOW;
    gpio.Alternate = ENC_R_A_AF;   /* GPIO_AF2_TIM4 */
    HAL_GPIO_Init(ENC_R_A_PORT, &gpio);

    htim4.Instance               = TIM4;
    htim4.Init.Prescaler         = 0U;
    htim4.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim4.Init.Period            = ENC_R_MAX_COUNT;   /* 0xFFFF */
    htim4.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim4.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;

    enc.EncoderMode   = TIM_ENCODERMODE_TI12;
    enc.IC1Polarity   = TIM_ICPOLARITY_RISING;
    enc.IC1Selection  = TIM_ICSELECTION_DIRECTTI;
    enc.IC1Prescaler  = TIM_ICPSC_DIV1;
    enc.IC1Filter     = 0x04U;
    enc.IC2Polarity   = TIM_ICPOLARITY_RISING;
    enc.IC2Selection  = TIM_ICSELECTION_DIRECTTI;
    enc.IC2Prescaler  = TIM_ICPSC_DIV1;
    enc.IC2Filter     = 0x04U;

    (void)HAL_TIM_Encoder_Init(&htim4, &enc);
    (void)HAL_TIM_Encoder_Start(&htim4, TIM_CHANNEL_ALL);

    /* Enable update interrupt for overflow extension */
    HAL_NVIC_SetPriority(TIM4_IRQn, 3U, 0U);
    HAL_NVIC_EnableIRQ(TIM4_IRQn);
    __HAL_TIM_ENABLE_IT(&htim4, TIM_IT_UPDATE);
}

/**
 * @brief  Initialise TIM5 as a 1 kHz interrupt source for the control loop.
 *
 * @details PSC = 99  → tick rate = 100 MHz / 100 = 1 MHz
 *          ARR = 999 → IRQ rate  = 1 MHz / 1000  = 1 kHz
 *          NVIC priority 1 (highest after SysTick which is 0).
 *          Timer is NOT started here — started in main() after all
 *          modules are ready, to prevent ISR firing during init.
 */
static void tim5_ctrl_loop_init(void)
{
    __HAL_RCC_TIM5_CLK_ENABLE();

    htim5.Instance               = CTRL_TIM_INSTANCE;   /* TIM5 */
    htim5.Init.Prescaler         = CTRL_TIM_PSC;        /* 99   */
    htim5.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim5.Init.Period            = CTRL_TIM_ARR;        /* 999  */
    htim5.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim5.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;

    (void)HAL_TIM_Base_Init(&htim5);

    HAL_NVIC_SetPriority(TIM5_IRQn, CTRL_TIM_PRIORITY, 0U);
    HAL_NVIC_EnableIRQ(TIM5_IRQn);

    /* Start immediately after modules_init() completes */
    (void)HAL_TIM_Base_Start_IT(&htim5);
}

/**
 * @brief  Initialise ADC1 with 7-channel DMA circular scan.
 *
 * @details Rank order (must match IR_IDX_* in pins.h):
 *            Rank 1  PA2 IN2  Right Side  receiver
 *            Rank 2  PA3 IN3  Left  Side  receiver
 *            Rank 3  PA4 IN4  Right Front receiver
 *            Rank 4  PA5 IN5  Left  Front receiver
 *            Rank 5  PA6 IN6  Right Angle receiver
 *            Rank 6  PA7 IN7  Left  Angle receiver
 *            Rank 7  PB0 IN8  Battery voltage divider
 *
 *          Sample time: 84 cycles per channel.
 *          Conversion is triggered by software inside ir_update().
 *          DMA circular mode — buffer is always up-to-date.
 */
static void adc1_ir_battery_init(void)
{
    ADC_ChannelConfTypeDef ch = {0};

    __HAL_RCC_ADC1_CLK_ENABLE();

    hadc1.Instance                   = IR_ADC_INSTANCE;   /* ADC1 */
    hadc1.Init.ClockPrescaler        = ADC_CLOCK_SYNC_PCLK_DIV4;
    hadc1.Init.Resolution            = ADC_RESOLUTION_12B;
    hadc1.Init.ScanConvMode          = ENABLE;
    hadc1.Init.ContinuousConvMode    = DISABLE;   /* Software-triggered */
    hadc1.Init.DiscontinuousConvMode = DISABLE;
    hadc1.Init.ExternalTrigConv      = ADC_SOFTWARE_START;
    hadc1.Init.ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc1.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
    hadc1.Init.NbrOfConversion       = IR_ADC_BUF_LEN;   /* 7 */
    hadc1.Init.DMAContinuousRequests = ENABLE;
    hadc1.Init.EOCSelection          = ADC_EOC_SEQ_CONV;

    (void)HAL_ADC_Init(&hadc1);

    /* Configure each rank */
    const ADC_ChannelConfTypeDef channels[IR_ADC_BUF_LEN] = {
        { .Channel = IR_RECV_RS_ADC_CH,    .Rank = IR_RECV_RS_ADC_RANK,    .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_LS_ADC_CH,    .Rank = IR_RECV_LS_ADC_RANK,    .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_RF_ADC_CH,    .Rank = IR_RECV_RF_ADC_RANK,    .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_LF_ADC_CH,    .Rank = IR_RECV_LF_ADC_RANK,    .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_R_ANG_ADC_CH, .Rank = IR_RECV_R_ANG_ADC_RANK, .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = IR_RECV_L_ANG_ADC_CH, .Rank = IR_RECV_L_ANG_ADC_RANK, .SamplingTime = ADC_SAMPLETIME_84CYCLES },
        { .Channel = BATT_ADC_CH,          .Rank = BATT_ADC_RANK,          .SamplingTime = ADC_SAMPLETIME_84CYCLES },
    };

    for (uint8_t i = 0U; i < IR_ADC_BUF_LEN; i++)
    {
        ch = channels[i];
        (void)HAL_ADC_ConfigChannel(&hadc1, &ch);
    }
}

/**
 * @brief  Initialise I2C1 at 400 kHz for MPU6500 and SSD1306 OLED.
 *
 * @details PB8 → I2C1_SCL (AF04), PB9 → I2C1_SDA (AF04).
 *          Both pins require external 4.7 kΩ pull-up resistors to 3.3 V.
 *          The STM32F411 I2C_CR2 timing register value for 400 kHz
 *          at 50 MHz APB1 clock: 0x0C2177.  (From AN4235 Table 8.)
 */
static void i2c1_init(void)
{
    GPIO_InitTypeDef gpio = {0};

    __HAL_RCC_I2C1_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* PB8 SCL, PB9 SDA — open-drain, AF04 */
    gpio.Pin       = IMU_SCL_PIN | IMU_SDA_PIN;
    gpio.Mode      = GPIO_MODE_AF_OD;
    gpio.Pull      = GPIO_NOPULL;   /* External pull-ups on PCB          */
    gpio.Speed     = GPIO_SPEED_FREQ_HIGH;
    gpio.Alternate = IMU_SCL_AF;    /* GPIO_AF4_I2C1 */
    HAL_GPIO_Init(IMU_SCL_PORT, &gpio);

    hi2c1.Instance             = IMU_I2C_INSTANCE;   /* I2C1 */
    hi2c1.Init.ClockSpeed      = IMU_I2C_SPEED;      /* 400 000 Hz */
    hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1     = 0U;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;

    (void)HAL_I2C_Init(&hi2c1);
}

/**
 * @brief  Initialise UART1 at 115200 baud for debug logging.
 *
 * @details UART1 TX is PA9 which is also TIM1_CH2 (motor PWM).
 *          These are mutually exclusive alternate functions — TIM1
 *          uses PA9 in AF01, UART1 would use AF07.
 *
 * @note   CONFLICT: PA9 = MOTOR_R_PWM (TIM1_CH2, AF01).
 *         Using UART1 on PA9 simultaneously is NOT possible.
 *
 *         OPTIONS:
 *         A. Use USB CDC (virtual COM port over the USB connector) —
 *            no extra pin needed.  Enable USB_OTG_FS in CubeMX.
 *            Replace HAL_UART_Transmit with CDC_Transmit_FS in logger.c.
 *            This is the RECOMMENDED approach for the Black Pill.
 *
 *         B. Reroute UART1 TX to PB6 (AF07) — but PB6 = ENC_R_A (TIM4).
 *            Also a conflict.
 *
 *         C. Use UART2: TX=PA2 (AF07) — but PA2 = IR_RECV_RS (ADC).
 *            Also a conflict.
 *
 *         D. Use UART6: TX=PC6 (AF08) — no conflict.  Requires an
 *            external USB-serial adapter on PC6.
 *
 *         E. Use SWO trace output (PA14, ITM) — works with ST-Link.
 *
 *         This init function is provided for reference.  Use Option A
 *         (USB CDC) by default.  See logger.c for the implementation.
 */
static void uart1_init(void)
{
    /* USB CDC is the recommended debug interface for this pin map.
     * If using UART6 on PC6, configure here instead.
     * logger.c handles the actual transmit function selection.         */

    huart1.Instance          = USART1;
    huart1.Init.BaudRate     = 115200U;
    huart1.Init.WordLength   = UART_WORDLENGTH_8B;
    huart1.Init.StopBits     = UART_STOPBITS_1;
    huart1.Init.Parity       = UART_PARITY_NONE;
    huart1.Init.Mode         = UART_MODE_TX;
    huart1.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;

    /* Intentionally not calling HAL_UART_Init here — logger.c selects
     * the interface (USB CDC or UART) at runtime based on build flags. */
}

/* =========================================================================
 * HARD FAULT HANDLER
 * ======================================================================= */

/**
 * @brief  HardFault exception handler.
 *
 * @details Disables motors immediately, then blinks the LED 10 times
 *          rapidly to signal a crash.  Loops forever — requires a
 *          hardware reset to recover.
 *
 *          During development: connect ST-Link and set a breakpoint here,
 *          then inspect the stack frame to identify the fault address.
 */
void HardFault_Handler(void)
{
    /* Disable motors — most important thing to do immediately */
    MOTOR_DISABLE();
    MOTOR_L_COAST();
    MOTOR_R_COAST();
    IR_ALL_EMITTERS_OFF();

    /* Rapid LED blink — 10 flashes then slow pulse */
    for (uint8_t i = 0U; i < 20U; i++)
    {
        LED_TOGGLE();
        /* Busy-wait — HAL_Delay (SysTick) may not work in HardFault  */
        for (volatile uint32_t d = 0U; d < 200000UL; d++) {}
    }

    while (1)
    {
        LED_TOGGLE();
        for (volatile uint32_t d = 0U; d < 2000000UL; d++) {}
    }
}
